services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development service configuration
  dev:
    build:
      context: .
      target: builder
    ports:
      - '3000:3000'
      - '24678:24678'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: pnpm dev
